### ISSUE TITLE
Failed links in db

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberindex-euler#13]
Juno writes failed link txs in postgres db

**Comment by cyborgshead** [comment]
Added tx code to schema and success check before indexing tx's msgs
https://github.com/cybercongress/cyberindex/commit/19af1cdb71ef52ced649dc5d185ceac9692129ad
@SaveTheAles please test this

**Comment by SaveTheAles** [comment]
There is some bug with `cyberlinks` table fill

**Comment by cyborgshead** [comment]
@SaveTheAles I fixed this already
