### ISSUE TITLE
More than one links in TX not tracked

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberindex-euler#20]
Tx with 2 links

https://cyberd.ai/transactions/07243D4BDE2ACD7C78E13A35BECFD62E9451E637083D6DCB624D16844513CBE4

But tracked only first link in a tx 

The tx hash key in cyberlink table is unique. Probably this is the thing.

**Comment by cyborgshead** [comment]
References:
https://github.com/cybercongress/cyberindex/commit/6225bfe891a90170516423faac8721fc01959fc3
https://github.com/cybercongress/cyberindex/commit/10167960d27bf2b5ccc402376e9e0c6ad4bd0dd2
