### ISSUE TITLE
Fix table naming

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberindex-euler#4]
It should be great to save consistent naming in all components of the system (e.g.  WP, API, network...)

This way we need:
**cyberlink** table name instead link
**object_from** column name instead CID_from
**object_to** column name instead CID_to
**subject**  column name instead agent
**txhash**  column name instead transaction

**Comment by cyborgshead** [comment]
Namings fixed in https://github.com/cybercongress/cyberindex/commit/cda0a25f2c5a3782b808694dce32c51036f2fad8
